spring:
    profiles: dev

server.port: 8081
    
rest:
    proxy:
        url: http://localhost:8080
        log: true
        mapping: /api/*
    oauth.client:
        auth_url: http://localhost:8080/oauth/authorize
        token_url: http://localhost:8080/oauth/token